INSERT INTO stores (
    business_name, business_type, tax_id, reg_no, website_url,
    house_number, street, city, state, country, zip_code,
    description, services, owner_id, twitter, facebook,
    instagram, email, phone, secondary_phone, opening_hours,
    closing_hours, delivery_options, return_policy, is_featured,
    ratings_count, average_rating, logo_url, created_at, updated_at
) VALUES
('David’s Handyman Services', 'Service', 'TX123456', 'RN123456', 'http://davids-handyman.com', '123', 'Maple Street', 'Lagos', 'Lagos State', 'Nigeria', '100001', 'Experienced handyman with a broad skill set.', 'Electrical Repairs, Plumbing', 1, 'https://twitter.com/davids_handyman', 'https://facebook.com/davids_handyman', 'https://instagram.com/davids_handyman', 'david@example.com', '08012345678', '08087654321', '08:00:00', '17:00:00', 'Same-day delivery', '7-day return policy', 1, 25, 4.5, 'http://example.com/logo1.jpg', NOW(), NOW()),
('Emily’s Home Services', 'Service', NULL, 'RN654321', 'http://emilys-homeservices.com', '456', 'Pine Street', 'Abuja', 'FCT', 'Nigeria', '200002', 'Versatile handywoman skilled in home maintenance tasks.', 'Furniture Assembly, Gardening', 2, 'https://twitter.com/emilys_homeservices', 'https://facebook.com/emilys_homeservices', 'https://instagram.com/emilys_homeservices', 'emily@example.com', '08023456789', '08098765432', '09:00:00', '18:00:00', 'Next-day delivery', '30-day return policy', 0, 15, 4.7, 'http://example.com/logo2.jpg', NOW(), NOW()),
('Michael’s Renovations', 'Construction', 'TX789012', NULL, NULL, '789', 'Oak Street', 'Ibadan', 'Oyo State', 'Nigeria', '300003', 'Expert in various home renovation projects.', 'Carpet Installation, Woodworking', 3, NULL, NULL, NULL, 'michael@example.com', '08034567890', NULL, '07:30:00', '16:30:00', 'Standard delivery', '14-day return policy', 1, 50, 4.9, 'http://example.com/logo3.jpg', NOW(), NOW()),
('Jessica’s Outdoor Services', 'Service', 'TX345678', 'RN345678', 'http://jessicas-outdoor.com', '101', 'Cedar Street', 'Kano', 'Kano State', 'Nigeria', NULL, 'Professionally trained in outdoor carpentry.', 'Deck Construction, Roof Repairs', 4, 'https://twitter.com/jessicas_outdoor', 'https://facebook.com/jessicas_outdoor', 'https://instagram.com/jessicas_outdoor', 'jessica@example.com', '08045678901', NULL, '08:30:00', '17:30:00', 'Express delivery', '7-day return policy', 0, 20, 4.8, 'http://example.com/logo4.jpg', NOW(), NOW()),
('Robert’s HVAC Services', 'Service', 'TX901234', NULL, 'http://roberts-hvac.com', '202', 'Birch Street', 'Port Harcourt', 'Rivers State', 'Nigeria', '400004', 'Licensed handyman specializing in HVAC systems.', 'Heating & Cooling Systems, Drain Cleaning', 5, 'https://twitter.com/roberts_hvac', 'https://facebook.com/roberts_hvac', 'https://instagram.com/roberts_hvac', 'robert@example.com', '08056789012', '08009876543', '07:00:00', '15:00:00', 'Standard delivery', '30-day return policy', 1, 30, 4.6, 'http://example.com/logo5.jpg', NOW(), NOW()),
('Jennifer’s Remodeling', 'Service', NULL, 'RN789456', 'http://jennifers-remodeling.com', '303', 'Spruce Street', 'Benin City', 'Edo State', 'Nigeria', '500005', 'Experienced in kitchen and bathroom remodeling.', 'Kitchen Remodeling, Flooring Installation', 6, 'https://twitter.com/jennifers_remodeling', 'https://facebook.com/jennifers_remodeling', 'https://instagram.com/jennifers_remodeling', 'jennifer@example.com', '08067890123', NULL, '08:00:00', '17:00:00', 'Next-day delivery', '14-day return policy', 0, 40, 4.4, 'http://example.com/logo6.jpg', NOW(), NOW()),
('James’ Plumbing Services', 'Service', 'TX654321', 'RN654321', 'http://james-plumbing.com', '404', 'Willow Street', 'Enugu', 'Enugu State', 'Nigeria', '600006', 'Skilled plumber with extensive experience.', 'Plumbing, Drain Cleaning', 7, 'https://twitter.com/james_plumbing', 'https://facebook.com/james_plumbing', 'https://instagram.com/james_plumbing', 'james@example.com', '08078901234', '08019876543', '08:00:00', '17:00:00', 'Standard delivery', '30-day return policy', 1, 35, 4.5, 'http://example.com/logo7.jpg', NOW(), NOW()),
('Sarah’s Home Repairs', 'Service', 'TX432109', 'RN432109', 'http://sarahs-homerepairs.com', '505', 'Fir Street', 'Jos', 'Plateau State', 'Nigeria', '700007', 'Reliable handyman services for home repairs.', 'Electrical Repairs, Wall Painting', 8, 'https://twitter.com/sarahs_homerepairs', 'https://facebook.com/sarahs_homerepairs', 'https://instagram.com/sarahs_homerepairs', 'sarah@example.com', '08089012345', '08029876543', '09:00:00', '18:00:00', 'Next-day delivery', '14-day return policy', 0, 20, 4.3, 'http://example.com/logo8.jpg', NOW(), NOW()),
('Charles’ Carpentry Services', 'Construction', 'TX876543', NULL, 'http://charles-carpentry.com', '606', 'Aspen Street', 'Abeokuta', 'Ogun State', 'Nigeria', '800008', 'Experienced carpenter with a focus on detail.', 'Woodworking, Deck Construction', 9, 'https://twitter.com/charles_carpentry', 'https://facebook.com/charles_carpentry', 'https://instagram.com/charles_carpentry', 'charles@example.com', '08090123456', NULL, '08:00:00', '17:00:00', 'Express delivery', '7-day return policy', 1, 25, 4.7, 'http://example.com/logo9.jpg', NOW(), NOW()),
('Anna’s Home Solutions', 'Service', 'TX543210', 'RN543210', 'http://annas-homesolutions.com', '707', 'Poplar Street', 'Calabar', 'Cross River State', 'Nigeria', NULL, 'All-in-one home solutions for various needs.', 'Furniture Assembly, Home Maintenance', 10, 'https://twitter.com/annas_homesolutions', 'https://facebook.com/annas_homesolutions', 'https://instagram.com/annas_homesolutions', 'anna@example.com', '08001234567', '08039876543', '09:00:00', '18:00:00', 'Standard delivery', '30-day return policy', 0, 30, 4.6, 'http://example.com/logo10.jpg', NOW(), NOW());
